# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborwatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbour',
            name='location',
            field=models.CharField(choices=[('Kagugu', 'kagugu'), ('kimironko', 'kimironko'), ('nyamagabe', 'nyamagabe'), ('kimihurura', 'kimihurura'), ('kabeza', 'kabeza'), ('Nyabugogo', 'Nyabugogo'), ('Kibagabaga', 'Kibagabaga'), ('simba s', 'simba s'), ('Kcc', 'Kcc')], max_length=30),
        ),
    ]
